sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
before_install:
# Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - 
before_deploy:
  - git add -f node_modules/
  # safelist
branches:
  only:
  - master
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master